### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [westonruter/webforms2#4]
Would you consider dual licensing under the MIT and GPL as jQuery, jQuery UI and others have done? I work with a number of Apache licensed projects, and would love the option to use and contribute to this library, but the GPL prevents that (as it's incompatible with the Apache license).

Thanks.

**Comment by westonruter** [comment]
Certainly. I think the only reason why it isn't dual-licensed is because
Google Code didn't allow multiple licenses. But I think Zoltan would agree
with the dual-license idea.

On Tue, Jan 24, 2012 at 10:58 AM, BigBlueHat - Web Manufacturer <
reply@reply.github.com

> wrote:
> 
> Would you consider dual licensing under the MIT and GPL as jQuery, jQuery
> UI and others have done? I work with a number of Apache licensed projects,
> and would love the option to use and contribute to this library, but the
> GPL prevents that (as it's incompatible with the Apache license).
> 
> Thanks.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/westonruter/webforms2/issues/4

## 

Weston Ruter
http://weston.ruter.net/
@westonruter http://twitter.com/westonruter - Google
Profilehttp://www.google.com/profiles/WestonRuter#about

**Comment by BigBlueHat** [comment]
Any word from Zoltan? :)

**Comment by zoltan-dulac** [comment]
Apologies for the late response.  Yes, I agree with releasing it under a dual license.  Let's see if I can change this now ....

**Comment by zoltan-dulac** [comment]
Actually ... I guess this something Weston has to change I believe.  So, if all that's needed is for me to say "I agree", then ... "I agree" :-)

**Comment by westonruter** [comment]
Wait, why/where do I have to change it?

On Mon, Feb 6, 2012 at 8:34 PM, Zoltan Hawryluk <
reply@reply.github.com

> wrote:
> 
> Actually ... I guess this something Weston has to change I believe.  So,
> if all that's needed is for me to say "I agree", then ... "I agree" :-)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/westonruter/webforms2/issues/4#issuecomment-3842453

## 

Weston Ruter
http://weston.ruter.net/
@westonruter http://twitter.com/westonruter -
LinkedInhttp://www.linkedin.com/in/westonruter-
Facebook https://www.facebook.com/westonruter -
Google+https://plus.google.com/u/0/113853198722136596993/about

**Comment by zoltan-dulac** [comment]
@weston: Doh!  Forgive my previous erroneous post.  Lack of sleep makes me delirious.  I have just updated webforms2 to be dual license in both the readme and the uncompressed script's header.

**Comment by westonruter** [comment]
Cheers!

**Comment by weston-zz** [comment]
Oh, it doesn't matter, wish u !
